name: travelkuy
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0 

flutter:
  uses-material-design: true

  # Folder assets yang sudah disesuaikan
  assets:
  #onboarding
    - assets/images/onboarding/ob1.jpg
    - assets/images/onboarding/ob2.png
    - assets/images/onboarding/ob3.png
    - assets/images/onboarding/ob4.png
    - assets/images/onboarding/ob5.png
    - assets/images/onboarding/ob6.jpg
  #special offer
    - assets/images/special_offer/Bus.png
    
    # route
    - assets/images/route/Beach.png
    - assets/images/route/Cityscape.png
    - assets/images/route/Landscape.png
    - assets/images/route/Nature.png
    

